"""Selection data: class, crate, reason and cut specification per file.

SELECTED maps repo-relative path -> dict(cls, crate, sha256, rust_module, adaptations,
                                        reason, cut, ranges, keep)
  sha256: SHA-256 of the complete upstream file at Pi v1.0.4
  rust_module: concrete Rust source path relative to apps/maple-agent
  adaptations: implementation-specific deviations, empty until recorded
  status: optional implementation state (pending, ported, adapted); pending by default
  cut:    member names removed (as printed by members.py)
  ranges: extra line ranges removed ("a-b")
  keep:   for files where only explicit line ranges are kept ("a-b")
EXCLUDE_RULES: (regex, reason) applied in order to every other file.
"""

import sys

sys.dont_write_bytecode = True

A = "packages/agent/src/"
I = "packages/ai/src/"
C = "packages/coding-agent/src/"

SELECTED = {
    # ---------------- pi-agent-core ----------------
    A + "agent-loop.ts": dict(cls="Port", crate="pi-agent-core", sha256="e773e822a2587caf314e6bb66ea6370fce3468b7eecd26d6a67afe673f81eabc", rust_module="crates/pi-agent-core/src/agent_loop.rs", adaptations=[], reason="Turn loop, tool batches, steering/follow-up drain points, length stops; the loop Maple owns"),
    A + "agent.ts": dict(cls="Port", crate="pi-agent-core", sha256="7024a3145a6ebc951a0f030164adb1dfb12d33d6e0dbbac15ef0efda49c87457", rust_module="crates/pi-agent-core/src/agent.rs", adaptations=[], reason="`Agent` state, queues, abort, awaited subscribers (persistence barrier)"),
    A + "types.ts": dict(cls="Port", crate="pi-agent-core", sha256="347efd535342c1d5fbd6b731168c57fcbb201a6652707f8e22e1b66fe3b69c2d", rust_module="crates/pi-agent-core/src/types.rs", adaptations=[], reason="`AgentMessage`, `AgentTool`, events, `StreamFn` contract and the hook types (`beforeToolCall`, `afterToolCall`, ...)"),
    A + "stream-fn.ts": dict(cls="Port", crate="pi-agent-core", sha256="1f9dee101a5ce1052558458d9ce47e53e05187224e879217899059a80d90bc45", rust_module="crates/pi-agent-core/src/stream_fn.rs", adaptations=[], reason="Default stream-function slot; stays unset because Maple always passes `streamFn`"),
    # ---------------- pi-ai ----------------
    I + "types.ts": dict(cls="Adapt", crate="pi-ai", sha256="a9e18401b3062f50c6b10cf31eb94082c0af09c685ea9dea6efa344cbedd5caf", rust_module="crates/pi-ai/src/types.rs", adaptations=[], reason="Message, usage, event, model and tool contracts; cut other APIs' option/compat types, image and classifier types, `TelemetryContext`",
                         cut=["KnownImageApi", "ImageApi", "KnownClassifierApi", "ClassifierApi", "ProviderImages", "ProviderClassifier", "ClassifierOptions", "ImagesOptions", "ProviderImagesOptions", "AnthropicAllowedFallbackModel", "ImagesFunction", "ClassifierFunction", "ImagesInputContent", "ImagesOutputContent", "ImagesContext", "ImagesStopReason", "AssistantImages", "ClassifierChoiceQuestion", "ClassifierScoreQuestion", "ClassifierBoolQuestion", "ClassifierQuestion", "ClassifierContext", "ClassifierChoiceAnswer", "ClassifierScoreAnswer", "ClassifierBoolAnswer", "ClassifierAnswer", "ClassifierStopReason", "ClassifierResult", "OpenAIResponsesCompat", "AnthropicMessagesCompat", "BedrockCompat", "MistralConversationsCompat", "ImageModel", "ClassifierModel"],
                         ranges=["1-8", "10-11"]),
    I + "api/openai-completions.ts": dict(cls="Adapt", crate="pi-ai", sha256="1ca201e5ec88b54982bf1d64c476b2885a80dee9eb1206be9f5dea260202cc60", rust_module="crates/pi-ai/src/api/openai_completions.rs", adaptations=[], reason="Chat-completions request builder and SSE chunk parser; the OpenAI SDK client, API-key check, Copilot/User-Agent headers, provider retry and SDK error formatting move to Maple's transport seam",
                                          cut=["hasHeader", "getClientApiKey", "createClient"], ranges=["38-38", "43-43", "45-45", "63-63"]),
    I + "api/constrained-sampling.ts": dict(cls="Port", crate="pi-ai", sha256="f795db4afbbdf2918b346a7f260841ca477c29b26bcdb1084e039697a715a22a", rust_module="crates/pi-ai/src/api/constrained_sampling.rs", adaptations=[], reason="`getJsonSchemaToolParameters` runs for every tool in `convertTools`; strict/grammar paths stay inert unless a tool and the model's compat ask for them"),
    I + "api/openai-prompt-cache.ts": dict(cls="Port", crate="pi-ai", sha256="78727b9b42d5c5cdc47d17f44d532cdf951cbee3b158cacfb3e640d8f792e8a4", rust_module="crates/pi-ai/src/api/openai_prompt_cache.rs", adaptations=[], reason="`clampOpenAIPromptCacheKey`, called by `buildParams`"),
    I + "api/simple-options.ts": dict(cls="Adapt", crate="pi-ai", sha256="f68b3e13a55a72214243b37eb85fa0532b67cfb22ac80ea3434eb5d26ae36616", rust_module="crates/pi-ai/src/api/simple_options.rs", adaptations=[], reason="Thinking budgets, max-token clamping, sampling params per level; only the `telemetryContext` forwarding line goes"),
    I + "api/transform-messages.ts": dict(cls="Port", crate="pi-ai", sha256="6d82d11a49213a4193e0d074f36d7af76e8a911b003104c0aa2c22569b2fe669", rust_module="crates/pi-ai/src/api/transform_messages.rs", adaptations=[], reason="Request repair: drop error/aborted turns, synthesize missing tool results, image placeholders, thinking/ID normalization"),
    I + "utils/event-stream.ts": dict(cls="Port", crate="pi-ai", sha256="147084657f76665ff7d6c8dcd6eb0745149e3aaee3e7b9c272b315a1b5679386", rust_module="crates/pi-ai/src/utils/event_stream.rs", adaptations=[], reason="Event stream with a final result (Rust channel/`Stream`)"),
    I + "utils/json-parse.ts": dict(cls="Port", crate="pi-ai", sha256="828440b19a64773f696ced9461166913ddaddd8479697fbde32d3f298872b153", rust_module="crates/pi-ai/src/utils/json_parse.rs", adaptations=[], reason="Streaming/partial and repaired JSON for tool arguments"),
    I + "utils/validation.ts": dict(cls="Port", crate="pi-ai", sha256="460786b57dead200e411b9afec916a5049c96ebcff4da082096456ac06d44fb7", rust_module="crates/pi-ai/src/utils/validation.rs", adaptations=[], reason="Tool-argument coercion and validation before any hook"),
    I + "utils/transcript.ts": dict(cls="Port", crate="pi-ai", sha256="e0814f35bdcc93b017fa45589a6920e46b5480b88fba01ef93e5d2d4e815f0f2", rust_module="crates/pi-ai/src/utils/transcript.rs", adaptations=[], reason="System-message replay, tool declarations, collapsing for endpoints without mid-conversation system messages"),
    I + "utils/estimate.ts": dict(cls="Port", crate="pi-ai", sha256="8df2512ca8c3e71eea5574b3d56c3569963e1fdabaef4bd17baaba86186c1840", rust_module="crates/pi-ai/src/utils/estimate.rs", adaptations=[], reason="Usage-anchored token estimate used by `simple-options` output clamping"),
    I + "utils/diagnostics.ts": dict(cls="Port", crate="pi-ai", sha256="06fcbc2347f65a43938078094a7118036b5f12e73147affb5c73cd72753443f0", rust_module="crates/pi-ai/src/utils/diagnostics.rs", adaptations=[], reason="Assistant-message diagnostics"),
    I + "utils/text.ts": dict(cls="Port", crate="pi-ai", sha256="d37c1825855c7fc71669a545b5b266810242c1c7e58d57228c0c143f29c1c544", rust_module="crates/pi-ai/src/utils/text.rs", adaptations=[], reason="Content-text and system-message rendering helpers"),
    I + "utils/hash.ts": dict(cls="Port", crate="pi-ai", sha256="2cdfce4af41810d1a92c7f0a55c78637a3173041038aafd85b378be345761ed8", rust_module="crates/pi-ai/src/utils/hash.rs", adaptations=[], reason="Short hashes used by the request builder"),
    I + "utils/headers.ts": dict(cls="Port", crate="pi-ai", sha256="423ded49de35ee755f62229ccd64bed6448739c78c6111226ff8e4a201cf9732", rust_module="crates/pi-ai/src/utils/headers.rs", adaptations=[], reason="Response-header records for `onResponse`"),
    I + "utils/sanitize-unicode.ts": dict(cls="Port", crate="pi-ai", sha256="f8ef2c957f9f13a77df45ebf344f1b852dfe8f2e3d164d815127ea7290c12e22", rust_module="crates/pi-ai/src/utils/sanitize_unicode.rs", adaptations=[], reason="Unpaired-surrogate removal in request text"),
    I + "utils/overflow.ts": dict(cls="Port", crate="pi-ai", sha256="2fa34713faa32430af3295ac25a10fd2e361cc0343b0f554491c16d2a2f44fc9", rust_module="crates/pi-ai/src/utils/overflow.rs", adaptations=[], reason="Context-overflow and recoverable-length classification"),
    I + "utils/retry.ts": dict(cls="Port", crate="pi-ai", sha256="5018e8d93a59f08426c3a45fd367dc789cb16ac4b472829dd5148f1d31bd335e", rust_module="crates/pi-ai/src/utils/retry.rs", adaptations=[], reason="Assistant-turn retry policy and retryable-error patterns (`retryAssistantCall`)"),
    I + "utils/uuid.ts": dict(cls="Port", crate="pi-ai", sha256="234a48d4b999e69188fdfa49173ccfa7887d947e443ef206cc30219515105a1f", rust_module="crates/pi-ai/src/utils/uuid.rs", adaptations=[], reason="Monotonic UUIDv7 for session and summary IDs (session-manager, compaction)"),
    I + "utils/provider-env.ts": dict(cls="Adapt", crate="pi-ai", sha256="3829251ae0674cef7ca09800cee9f46d4e305770129b72b822ea2f6f85efe675", rust_module="crates/pi-ai/src/utils/provider_env.rs", adaptations=[], reason="`getProviderEnvValue` for `PI_CACHE_RETENTION`; the Bun `/proc/self/environ` fallback goes",
                                      cut=["procEnvCache", "getBunSandboxEnvValue"]),
    I + "utils/model-operations.ts": dict(cls="Adapt", crate="pi-ai", sha256="d024c049a08df73498362f297ca10c45a401fb5a3364c0a4d7890ec92a3c4763", rust_module="crates/pi-ai/src/utils/model_operations.rs", adaptations=[], reason="Keep `getModelType`/`isModelType` (used by `modelsAreEqual`); image/classifier asserts go",
                                          cut=["assertChatModel", "assertImageModel", "assertClassifierModel", "imageErrorResult", "classifierErrorResult"], ranges=["1-14"]),
    I + "models.ts": dict(cls="Adapt", crate="pi-ai", sha256="62e4a8cb3d52d76f3eb2286f23436f5cd6d4d33dc56cebfa4a528c6a6d4d525e", rust_module="crates/pi-ai/src/models.rs", adaptations=[], reason="Keep the request-option and refresh types (`ModelsRequestTransforms`, `ModelsSimpleStreamOptions`, ..., lines 97-119) and the pure helpers `calculateCost`, `getSupportedThinkingLevels`, `clampThinkingLevel`, `modelsAreEqual`, `hasApi` (lines 1194-1261); the `Models` registry, `Provider` and `createProvider` go",
                          keep=["97-119", "1194-1261"]),
    I + "session-resources.ts": dict(cls="Port", crate="pi-ai", sha256="3e6d76f038d6b7fe515ede0b6650d41a7df16eb4b3a9f1aa91c9de329ff092e2", rust_module="crates/pi-ai/src/session_resources.rs", adaptations=[], reason="Session-resource cleanup registry called from `AgentSession.dispose()`"),
    I + "providers/faux.ts": dict(cls="Adapt", crate="pi-ai", sha256="dcf37d154680cef0fa5188efd4881450073c5342a9b56cc9e25cee9b9f1ccfcc", rust_module="crates/pi-ai/src/providers/faux.rs", adaptations=[], reason="Scripted provider for ported tests; `fauxProvider()` returns a handle without the excluded `createProvider` wrapper",
                                  cut=["fauxProvider"]),
    I + "auth/types.ts": dict(cls="Adapt", crate="pi-ai", sha256="8fb9acd4c998502826b22df2d88bcded441cc473a606c5b7bdf21271afd1a74a", rust_module="crates/pi-ai/src/auth/types.rs", adaptations=[], reason="Keep the request-auth types `ModelAuth`, `AuthResult`, `AuthCheck`, `AuthType`, `AuthOperationOptions`; credential stores and login types go",
                              cut=["ApiKeyCredential", "OAuthCredentials", "OAuthCredential", "Credential", "CredentialInfo", "CredentialStore", "AuthContext", "AuthPrompt", "AuthInfoLink", "AuthEvent", "AuthInteraction", "ProviderAuthInteraction", "ApiKeyAuth", "LoginOptions", "OAuthAuth", "ProviderAuth"]),
    # ---------------- pi-coding-agent ----------------
    C + "core/agent-session.ts": dict(cls="Adapt", crate="pi-coding-agent", sha256="86bb6d4ed757c6fa4b4154c938c900aafbddf8aa067587098b6154a33f844c9a", rust_module="crates/pi-coding-agent/src/core/agent_session.rs", adaptations=[], reason="Orchestration: hook wiring, persistence on `message_end`, projection, prompt pipeline, queues, model/thinking selection, compaction, tree navigation, retry, extensions; named features cut (see exclusions)",
                                      cut=["ModelCycleResult", "_addPersistedDefaultToNonEmptyScope", "cycleModel", "_cycleScopedModel", "_cycleAvailableModel", "summarizeForBugReport", "cacheWarmingStatus", "setCacheWarmingMode", "_cacheWarmer", "executeBash", "recordBashResult", "abortBash", "isBashRunning", "hasPendingBashMessages", "_flushPendingBashMessages", "_bashAbortControllers", "_pendingBashMessages", "exportToHtml", "_executeNestedToolCall", "_nestedToolCalls", "routedModel", "_recordSelection", "_getRequiredRequestAuth"]),
    C + "core/agent-session-runtime.ts": dict(cls="Port", crate="pi-coding-agent", sha256="b163ce35d2b6e3ba1fc080c0674044a3f1cd9faec93cc2ed015e31b69780bf4a", rust_module="crates/pi-coding-agent/src/core/agent_session_runtime.rs", adaptations=[], reason="Single active session; `newSession`, `switchSession`, `fork`, `importFromJsonl`; `session_before_switch`/`_fork`"),
    C + "core/agent-session-services.ts": dict(cls="Adapt", crate="pi-coding-agent", sha256="c69826f519aa21b2dc04768eb63b0d10e88be071195beaf43bb1292dec187d01", rust_module="crates/pi-coding-agent/src/core/agent_session_services.rs", adaptations=[], reason="cwd-bound services; `modelRuntime` becomes required, extension provider/virtual-model flushes and CLI flag values go",
                                               ranges=["82-128", "140-146", "158-193"]),
    C + "core/sdk.ts": dict(cls="Adapt", crate="pi-coding-agent", sha256="cb1872d664f64a359c9efb93fd7215902a90c499d18367ede2d07da981cdfa07", rust_module="crates/pi-coding-agent/src/core/sdk.rs", adaptations=[], reason="`createAgentSession`: model/thinking restore, `streamFn` -> `modelRuntime.streamSimple`, provider hooks; `findInitialModel`, cache warmer, attribution headers, network timeouts and tool-factory re-exports go",
                            ranges=["14-14", "16-16", "22-40", "125-138", "226-235", "238-240", "316-321", "327-328", "333-333", "337-342", "349-363", "404-411"]),
    C + "core/messages.ts": dict(cls="Port", crate="pi-coding-agent", sha256="5397e3c96c9504266e4ee8b6e88d5098b3280ee7dbb0c687b74708c62a06c8d4", rust_module="crates/pi-coding-agent/src/core/messages.rs", adaptations=[], reason="Coding-agent roles and `convertToLlm`"),
    C + "core/defaults.ts": dict(cls="Port", crate="pi-coding-agent", sha256="e05e32e5613066667b52fa1d8864fec27b3564636f93af7983f53984bce02955", rust_module="crates/pi-coding-agent/src/core/defaults.rs", adaptations=[], reason="Default thinking level and level options"),
    C + "core/event-bus.ts": dict(cls="Port", crate="pi-coding-agent", sha256="fe5c39a57081fb9674c5bdc8c4bc6779bb8524c8895afc337af5ea517bdc71a2", rust_module="crates/pi-coding-agent/src/core/event_bus.rs", adaptations=[], reason="`pi.events` bus between extensions"),
    C + "core/session-cwd.ts": dict(cls="Port", crate="pi-coding-agent", sha256="581c849ce1ccb50da0ee9eabb3c34b80aed757aafcb79784349229e50df4d727", rust_module="crates/pi-coding-agent/src/core/session_cwd.rs", adaptations=[], reason="Missing working directory on resume"),
    C + "core/usage-totals.ts": dict(cls="Port", crate="pi-coding-agent", sha256="8b18dd04d65e90af9b331cd5aa23d7891aab8a296f38a6026ce17a098d674ee9", rust_module="crates/pi-coding-agent/src/core/usage_totals.rs", adaptations=[], reason="Session usage totals (stats, context ring input)"),
    C + "core/system-prompt.ts": dict(cls="Adapt", crate="pi-coding-agent", sha256="5e28c82634113d0cca7ff5da6fa94e27aaae80e461cd5664ced9dbcef6f89089", rust_module="crates/pi-coding-agent/src/core/system_prompt.rs", adaptations=[], reason="Named sections and section diffs; the `docs` section's Pi doc paths become host-supplied"),
    C + "core/model-registry.ts": dict(cls="Adapt", crate="pi-coding-agent", sha256="f4ced2d92df9097647aba7da3ae0bb273fa8089e966be15dba880db51d5dee0b", rust_module="crates/pi-coding-agent/src/core/model_registry.rs", adaptations=[], reason="`ctx.modelRegistry` facade over the `ModelRuntime` seam; provider/virtual-model registration, classify and image methods go",
                                       cut=["findOfType", "getProvider", "getModelsOfType", "getAvailableOfType", "getModelOfType", "classify", "generateImages", "registerProvider", "unregisterProvider", "registerVirtualModel", "unregisterVirtualModel", "getRegisteredProviderConfig", "getRegisteredNativeProvider", "getRegisteredProviderIds", "getProviderAuthStatus"]),
    C + "core/session-manager.ts": dict(cls="Port", crate="pi-coding-agent", sha256="450d82c529933214e088b8422f00061815e617f352f6c834689787a314064bff", rust_module="crates/pi-coding-agent/src/core/session_manager.rs", adaptations=[], reason="Entry tree, migrations, context building, append API, labels, branching, and the JSONL file store (preserves Pi's JSONL format)"),
    C + "core/session-export.ts": dict(cls="Port", crate="pi-coding-agent", sha256="8ec53e13bd4bc9097e4f7640e2fd2e58ffbbdcadce6df5efdf5cb5622f98d285", rust_module="crates/pi-coding-agent/src/core/session_export.rs", adaptations=[], reason="JSONL export of the current branch"),
    C + "core/compaction/compaction.ts": dict(cls="Adapt", crate="pi-coding-agent", sha256="d5aebd41333957b57fa3f1bee2a18b3c00b5d47bb1b4af6f913cf8cd791099c8", rust_module="crates/pi-coding-agent/src/core/compaction/compaction.rs", adaptations=[], reason="Thresholds, cut points, summaries, own estimator; `completeSummarization` always gets `streamFn` (the `completeSimple` fallback goes)"),
    C + "core/compaction/utils.ts": dict(cls="Port", crate="pi-coding-agent", sha256="cc0baada8a2e31bcf1dbc18948c69ba2264fb2ad4d2c583ceb772fd3c3233674", rust_module="crates/pi-coding-agent/src/core/compaction/utils.rs", adaptations=[], reason="Summary prompt, conversation serialization, file-operation lists"),
    C + "core/compaction/branch-summarization.ts": dict(cls="Port", crate="pi-coding-agent", sha256="0279195d2cddfe99d4e42a1327d18c7f55ff15a8807d2c5d6cd465b2ab163011", rust_module="crates/pi-coding-agent/src/core/compaction/branch_summarization.rs", adaptations=[], reason="Branch summaries for tree navigation: entries back to the common ancestor, budgeted preparation, summary prompt"),
    C + "core/extensions/types.ts": dict(cls="Adapt", crate="pi-coding-agent", sha256="33be19555ad54f9e10a3436ce51f54bd6b27cc870a7d9ecc0e4997aeeaa3ae0b", rust_module="crates/pi-coding-agent/src/core/extensions/types.rs", adaptations=[], reason="Event/result types, contexts, `ToolDefinition`, `ExtensionAPI` in Pi's shape; terminal UI, renderers, shortcuts, flags, custom providers, virtual models, user bash and built-in-tool event variants go",
                                         cut=["TerminalInputHandler", "WorkingIndicatorOptions", "AutocompleteProviderFactory", "EditorFactory", "ToolRenderResultOptions", "ToolRenderContext", "ToolRenderers", "ToolRendererResolver", "UserBashEvent", "BashToolCallEvent", "PowerShellToolCallEvent", "ReadToolCallEvent", "EditToolCallEvent", "WriteToolCallEvent", "GrepToolCallEvent", "FindToolCallEvent", "LsToolCallEvent", "BashToolResultEvent", "PowerShellToolResultEvent", "ReadToolResultEvent", "EditToolResultEvent", "WriteToolResultEvent", "GrepToolResultEvent", "FindToolResultEvent", "LsToolResultEvent", "isBashToolResult", "isPowerShellToolResult", "isReadToolResult", "isEditToolResult", "isWriteToolResult", "isGrepToolResult", "isFindToolResult", "isLsToolResult", "UserBashEventResult", "MessageRenderOptions", "MarkdownTransformContext", "MarkdownTransformer", "EntryRenderOptions", "MessageRenderer", "EntryRenderer", "ExtensionVirtualModel", "ProviderConfig", "ProviderModelConfigBase", "ProviderChatModelConfig", "ProviderImageModelConfig", "ProviderClassifierModelConfig", "ProviderModelConfig", "ExtensionFlag", "ExtensionShortcut"],
                                         ranges=["162-164", "168-186", "189-209", "213-238", "242-299", "582-584", "637-646", "1328-1356", "1588-1591", "1624-1624", "1643-1686", "1763-1836", "1863-1876"]),
    C + "core/extensions/runner.ts": dict(cls="Adapt", crate="pi-coding-agent", sha256="2a3bd7f81623928070eb956cdac37b861a787297046f9ce7af0522ff6d41a98a", rust_module="crates/pi-coding-agent/src/core/extensions/runner.rs", adaptations=[], reason="Dispatch order, error/cancel/chaining rules, contexts, `ui_prompt_*`; keybindings, renderers, flags, user bash and cache-warming handlers go",
                                          cut=["RESERVED_KEYBINDINGS_FOR_EXTENSION_CONFLICTS", "BuiltInKeyBindings", "buildBuiltinKeybindings", "isUserBashEventResult", "getShortcuts", "getShortcutDiagnostics", "shortcutDiagnostics", "getMessageRenderer", "getMarkdownTransformers", "resolveToolRenderers", "getEntryRenderer", "getFlags", "setFlagValue", "getFlagValues", "emitCacheWarmingDecision", "emitUserBash"]),
    C + "core/extensions/loader.ts": dict(cls="Adapt", crate="pi-coding-agent", sha256="0177db97c7e35ea39cdab53124c04dbf6e045ac379670bcae0b4e1269002eb3a", rust_module="crates/pi-coding-agent/src/core/extensions/loader.rs", adaptations=[], reason="`createExtensionRuntime`, `createExtensionAPI`, factory loading (`loadExtensionFromFactory`) for compiled-in Rust extensions; jiti/TypeScript loading, discovery, shortcuts, flags, renderers, providers, virtual models go",
                                          cut=["require", "isNodeSeaBinary", "isTypeScriptSourceRuntime", "usesEmbeddedModules", "createJitiPromise", "getCreateJiti", "virtualModulesPromise", "getVirtualModules", "_aliases", "getAliases", "extensionCacheCwd", "extensionCacheGeneration", "extensionCache", "ExtensionCacheToken", "clearExtensionCache", "useExtensionCacheCwd", "isCurrentCacheToken", "loadExtensionModule", "loadExtension", "loadExtensionsInternal", "loadExtensions", "loadExtensionsCached", "isExtensionFile", "resolveExtensionEntries", "discoverExtensionsInDir", "discoverAndLoadExtensions"],
                                          ranges=["320-380", "456-470", "500-515"]),
    C + "core/extensions/wrapper.ts": dict(cls="Port", crate="pi-coding-agent", sha256="7783d9e41dcb99fd10ebdd4e3d7aa4cef84fcf387f42be95265a5b7f6dcee14b", rust_module="crates/pi-coding-agent/src/core/extensions/wrapper.rs", adaptations=[], reason="Wraps registered tools for the loop"),
    C + "core/tools/tool-definition-wrapper.ts": dict(cls="Port", crate="pi-coding-agent", sha256="bae3cdd9f2aa21fb168ef42a47584f3b19536c0815ec14d94389af530eef9358", rust_module="crates/pi-coding-agent/src/core/tools/tool_definition_wrapper.rs", adaptations=[], reason="`ToolDefinition` <-> `AgentTool` wrappers (Maple's tools enter here)"),
    C + "core/tools/truncate.ts": dict(cls="Port", crate="pi-coding-agent", sha256="8e4507c3ed7ca7548cf7c2d7f77d07f2ae63a38b756789cbb44e9062db6c8762", rust_module="crates/pi-coding-agent/src/core/tools/truncate.rs", adaptations=[], reason="Head/tail/middle truncation helpers; used by the MCP tool adapter and available to Maple's tools"),
    C + "utils/output-files.ts": dict(cls="Port", crate="pi-coding-agent", sha256="a7ad819c4087b6f3ac79147d5e052718e181b105efc112be16a779a78a333620", rust_module="crates/pi-coding-agent/src/utils/output_files.rs", adaptations=[], reason="Private temp files for full truncated output (MCP adapter)"),
    C + "core/skills.ts": dict(cls="Port", crate="pi-coding-agent", sha256="8dcc644dbabbb34238f609ecf191c0da370d74873ccaccaf3c3cd0e7703d9431", rust_module="crates/pi-coding-agent/src/core/skills.rs", adaptations=[], reason="Agent Skills discovery, validation and prompt listing"),
    C + "core/prompt-templates.ts": dict(cls="Port", crate="pi-coding-agent", sha256="11db52a6bea6f3f094c6f533d4a3162462bdef4693f238ba1a8a1be6729d4545", rust_module="crates/pi-coding-agent/src/core/prompt_templates.rs", adaptations=[], reason="Prompt templates and argument expansion"),
    C + "core/resource-loader.ts": dict(cls="Adapt", crate="pi-coding-agent", sha256="dbe87c11983b8dac949377904f4cf0511155771498ba88d2fefb0cd0d5dd9e28", rust_module="crates/pi-coding-agent/src/core/resource_loader.rs", adaptations=[], reason="Context files (`AGENTS.md`/`CLAUDE.md`), `SYSTEM.md`/`APPEND_SYSTEM.md`, skills, prompts, extension sets from factories; themes and TypeScript-package warnings go",
                                        cut=["HOST_PROVIDED_EXTENSION_PACKAGES", "collectExtensionPackageWarnings", "getThemes", "loadThemes", "loadThemesFromDir", "loadThemeFromFile", "dedupeThemes", "updateThemesFromPaths", "themes", "themeDiagnostics", "themesOverride", "noThemes", "additionalThemePaths", "lastThemePaths", "extensionThemeSourceInfos"]),
    C + "core/package-manager.ts": dict(cls="Adapt", crate="pi-coding-agent", sha256="c571e652abec58e1302177137e6640c228afa1d68089afd904d3073693691863", rust_module="crates/pi-coding-agent/src/core/package_manager.rs", adaptations=[], reason="Local resource discovery (conventional dirs, `.agents/skills` up to the git root, `!`/`+`/`-` patterns, built-in extension toggles); the npm/git installer, theme and extension-file discovery go",
                                        cut=["getEnv", "NETWORK_TIMEOUT_MS", "UPDATE_CHECK_CONCURRENCY", "GIT_UPDATE_CONCURRENCY", "isOfflineModeEnabled", "isExactNpmVersion", "getNpmVersionRange", "ProgressEvent", "ProgressCallback", "PackageUpdate", "ConfiguredPackage", "PackageManager", "NpmSource", "LocalSource", "ParsedSource", "InstalledSourceScope", "ConfiguredUpdateSource", "NpmUpdateTarget", "GitUpdateTarget", "PackageFilter", "FILE_PATTERNS", "getExtensionTempFolder", "isOverridePattern", "hasGlobPattern", "expandPackageGlob", "collectFiles", "collectAutoThemeEntries", "resolveExtensionEntries", "collectAutoExtensionEntries", "collectResourceFiles", "globalNpmRoot", "globalNpmRootCommandKey", "progressCallback", "setProgressCallback", "addSourceToSettings", "removeSourceFromSettings", "getInstalledPath", "emitProgress", "withProgress", "resolveExtensionSources", "listConfiguredPackages", "install", "installAndPersist", "remove", "removeAndPersist", "update", "updateConfiguredSources", "shouldUpdateNpmSource", "updateNpmBatch", "installNpmBatch", "checkForAvailableUpdates", "resolvePackageSources", "findAutoloadDeltaBase", "resolveLocalExtensionSource", "installParsedSource", "getPackageSourceString", "getSourceMatchKeyForInput", "getSourceMatchKeyForSettings", "buildNoMatchingPackageMessage", "findSuggestedConfiguredSource", "packageSourcesMatch", "normalizePackageSourceForSettings", "parseSource", "installedNpmMatchesConfiguredVersion", "npmHasAvailableUpdate", "getInstalledNpmVersion", "getLatestNpmVersion", "gitHasAvailableUpdate", "getRemoteGitHead", "getLocalGitUpdateTarget", "getGitUpstreamRef", "runGitRemoteCommand", "runWithConcurrency", "getPackageIdentity", "dedupePackages", "parseNpmSpec", "assertProjectTrustedForScope", "getNpmCommand", "getPackageManagerName", "runNpmCommand", "getGitDependencyInstallArgs", "runNpmCommandSync", "getNpmInstallArgs", "installNpm", "uninstallNpm", "installGit", "updateGit", "hasMissingGitDependencies", "repairMissingGitDependencies", "getGitUpdateMarkerPath", "cleanAndInstallGitDependencies", "ensureGitRef", "refreshTemporaryGitSource", "removeGit", "pruneEmptyGitParents", "ensureNpmProject", "ensureGitIgnore", "getNpmInstallRoot", "getGlobalNpmRoot", "getPnpmGlobalPackagePath", "getManagedNpmInstallPath", "getLegacyGlobalNpmInstallPath", "getNpmInstallPath", "getGitInstallPath", "getGitInstallRoot", "getTemporaryDir", "resolveManagedPath", "getBaseDirForScope", "resolvePath", "collectPackageResources", "collectDefaultResources", "applyPackageFilter", "applyPackageDeltaFilter", "collectManifestFiles", "addManifestEntries", "collectFilesFromManifestEntries", "spawnCommand", "spawnCaptureCommand", "runCommandCapture", "runCommand", "runCommandSync"]),
    C + "core/settings-manager.ts": dict(cls="Adapt", crate="pi-coding-agent", sha256="535c679f41f769d9129ffec5521508241162c9dfe0a9c7782157b193eb0e5664", rust_module="crates/pi-coding-agent/src/core/settings_manager.rs", adaptations=[], reason="Scopes, deep merge, `defaultTools` modifiers, per-model overrides, file/in-memory storage, migration, write queue; agent settings kept, terminal/display/network/installer/telemetry settings go",
                                         cut=["TerminalSettings", "TuiMode", "FullscreenExitOutput", "MermaidRenderingMode", "CACHE_WARMING_MODES", "CacheWarmingMode", "MarkdownSettings", "WarningSettings", "CodemodeMode", "CodemodeSettings", "QuietStartup", "PackageSource", "getLastChangelogVersion", "setLastChangelogVersion", "getThemeSetting", "getTheme", "setTheme", "getHttpIdleTimeoutMs", "setHttpIdleTimeoutMs", "getCacheWarmingMode", "setCacheWarmingMode", "getWebSocketConnectTimeoutMs", "getHideThinkingBlock", "getShowCacheMissNotices", "getExternalEditorCommand", "setHideThinkingBlock", "setShowCacheMissNotices", "getShellPath", "setShellPath", "getQuietStartup", "setQuietStartup", "getShellCommandPrefix", "setShellCommandPrefix", "getNpmCommand", "setNpmCommand", "getCollapseChangelog", "setCollapseChangelog", "getEnableInstallTelemetry", "setEnableInstallTelemetry", "getEnableAnalytics", "getTrackingId", "setEnableAnalytics", "getOrCreateDeviceId", "getPackages", "setPackages", "setProjectPackages", "getThemePaths", "setThemePaths", "setProjectThemePaths", "getTerminalCapabilityOverrides", "getShowImages", "setShowImages", "getImageWidthCells", "setImageWidthCells", "getClearOnShrink", "setClearOnShrink", "getShowTerminalProgress", "setShowTerminalProgress", "getTuiMode", "setTuiMode", "getFullscreenExitOutput", "setFullscreenExitOutput", "getFullscreenScrollbar", "setFullscreenScrollbar", "getFullscreenCopyOnSelect", "setFullscreenCopyOnSelect", "getFullscreenWheelScrollLines", "setFullscreenWheelScrollLines", "getEnabledModels", "setEnabledModels", "getDoubleEscapeAction", "setDoubleEscapeAction", "getTreeFilterMode", "setTreeFilterMode", "getShowHardwareCursor", "setShowHardwareCursor", "getEditorPaddingX", "setEditorPaddingX", "getOutputPad", "setOutputPad", "getAutocompleteMaxVisible", "setAutocompleteMaxVisible", "getCodeBlockIndent", "getMermaidRenderingMode", "setMermaidRenderingMode", "getWarnings", "setWarnings", "parseTimeoutSetting"], ranges=["16-16"]),
    C + "core/settings-diagnostics.ts": dict(cls="Port", crate="pi-coding-agent", sha256="8ef3554ff841468a2493d9bab2754aa7a305471ea5754e54efccc363fe0dd0e1", rust_module="crates/pi-coding-agent/src/core/settings_diagnostics.rs", adaptations=[], reason="Deduplicates settings errors into runtime diagnostics"),
    C + "core/project-trust.ts": dict(cls="Port", crate="pi-coding-agent", sha256="39d5874a2a001ae7ac797ea297e31bf061eff07f9b2883f3eeaf6d3e1f5637ba", rust_module="crates/pi-coding-agent/src/core/project_trust.rs", adaptations=[], reason="Trust decision order and the `project_trust` hook"),
    C + "core/trust-manager.ts": dict(cls="Port", crate="pi-coding-agent", sha256="3098117ebea573afa6be81d669b2b0fe9cbc948cb4c10ef4ef12e54ca6758cac", rust_module="crates/pi-coding-agent/src/core/trust_manager.rs", adaptations=[], reason="`trust.json` store and the trust-requiring resource list"),
    C + "config.ts": dict(cls="Adapt", crate="pi-coding-agent", sha256="b3b77644910d3fac28a06625e90f993a8c1bc6c9458f148c723e64e0c99eb23e", rust_module="crates/pi-coding-agent/src/config.rs", adaptations=[], reason="`piConfig` name/config-dir conventions, `getAgentDir`, settings/prompts/sessions paths; package.json reading becomes host config, install/self-update/asset paths go",
                          keep=["556-591", "599-611", "626-631", "641-651"]),
    C + "core/source-info.ts": dict(cls="Port", crate="pi-coding-agent", sha256="52648af6e9bb29858ece4eaeccedd960c5de8a0ac4ec25c0ee851ff00de27f5c", rust_module="crates/pi-coding-agent/src/core/source_info.rs", adaptations=[], reason="Resource provenance"),
    C + "core/diagnostics.ts": dict(cls="Port", crate="pi-coding-agent", sha256="1914431098db1b4638e4fb3582ac22e8125356c4ab024671494f565c6d5ffb39", rust_module="crates/pi-coding-agent/src/core/diagnostics.rs", adaptations=[], reason="Resource diagnostics type"),
    C + "utils/frontmatter.ts": dict(cls="Port", crate="pi-coding-agent", sha256="99142d78b94e658e0be65cf05046be8069b3700168a683e0af64219ad903bcd6", rust_module="crates/pi-coding-agent/src/utils/frontmatter.rs", adaptations=[], reason="YAML frontmatter for skills and templates"),
    C + "utils/paths.ts": dict(cls="Adapt", crate="pi-coding-agent", sha256="64c3ebef724fa21ed0042e127908b4323a5d2f1b8aaa91eee550442332fe8502", rust_module="crates/pi-coding-agent/src/utils/paths.rs", adaptations=[], reason="Path normalization; `markPathIgnoredByCloudSync` (installer only) goes",
                               cut=["markPathIgnoredByCloudSync"], ranges=["5-5"]),
    C + "utils/text.ts": dict(cls="Port", crate="pi-coding-agent", sha256="bb323f9607c499115b532021f4f0163c6df04d834aee9c32c3c77b273bd2d7c6", rust_module="crates/pi-coding-agent/src/utils/text.rs", adaptations=[], reason="BOM helpers"),
    C + "utils/sleep.ts": dict(cls="Port", crate="pi-coding-agent", sha256="41bb3a7cccc0420483993d6fbc4e85d7cc1ab5a4ec46ce440deaae224f1005fc", rust_module="crates/pi-coding-agent/src/utils/sleep.rs", adaptations=[], reason="Abortable sleep for auto-retry backoff"),
    C + "core/mcp-servers.ts": dict(cls="Port", crate="pi-coding-agent", sha256="0aaad23b26f31f743bdd117754f4c871ea821279bf68f8ba5d71eccbb1602c6a", rust_module="crates/pi-coding-agent/src/core/mcp_servers.rs", adaptations=[], reason="`registerMcpServer` registry, config validation, exposure rules, tool-name matchers used by the core"),
    C + "extensions/mcp/tools.ts": dict(cls="Adapt", crate="pi-coding-agent", sha256="cf7495e4ad62c3252fc583d6c45046f316977a790b5f14fae1bcd1154384babb", rust_module="crates/pi-coding-agent/src/extensions/mcp/tools.rs", adaptations=[], reason="MCP tool -> Pi tool adapter: `mcp__<server>__<tool>` names, result conversion, 20 KB middle truncation; terminal renderers go",
                                        cut=["createMcpToolRenderers"], ranges=["23-23", "33-36"]),
    C + "core/exec.ts": dict(cls="Adapt", crate="pi-coding-agent", sha256="1a55e7416847ea0c548775b28596bb817c8cd4aa97bc36b8da7403959fcd350f", rust_module="crates/pi-coding-agent/src/core/exec.rs", adaptations=[], reason="`pi.exec` for extensions; `waitForChildProcess` becomes `tokio::process`"),
    C + "core/slash-commands.ts": dict(cls="Adapt", crate="pi-coding-agent", sha256="f0fee97e4b10d337593736ff8d9370fe5ea2c713d357397dba88c69677f07ce6", rust_module="crates/pi-coding-agent/src/core/slash_commands.rs", adaptations=[], reason="`SlashCommandInfo` types for `getCommands()`; the terminal's built-in command list goes",
                                       cut=["BuiltinSlashCommand", "BUILTIN_SLASH_COMMANDS"]),
    C + "core/virtual-models.ts": dict(cls="Adapt", crate="pi-coding-agent", sha256="dd836e0623b57bba55fa99b73738427e089a80599a45acc86d7b28219fa26519", rust_module="crates/pi-coding-agent/src/core/virtual_models.rs", adaptations=[], reason="Keep the read-only restore helpers (`getBranchSelection`, `isVirtualModel`, `findLatestResponse`, state lookup); routing and registration go",
                                       cut=["THINKING_LEVELS", "ModelRouteReason", "ModelRouteRequest", "ModelRoute", "VirtualModelDefinition", "createVirtualModel", "unroutedStream", "withVirtualModels"]),
    C + "core/footer-data-provider.ts": dict(cls="Adapt", crate="pi-coding-agent", sha256="024ae5b3f50a15db9c149f644845ffb267df838b3a555a0756db95043e05a0e2", rust_module="crates/pi-coding-agent/src/core/footer_data_provider.rs", adaptations=[], reason="Keep `findGitPaths` for the context-file worktree rule (`resource-loader.ts:215`); the footer data provider goes",
                                             keep=["6-47"]),
    C + "utils/image-process.ts": dict(cls="Port", crate="pi-coding-agent", sha256="fffb65fba877607644f8028c0f24aa6e74228e15427e112ee367e7983f2a79e5", rust_module="crates/pi-coding-agent/src/utils/image_process.rs", adaptations=[], reason="Prompt/tool-result image normalization contract"),
    C + "utils/tool-result-images.ts": dict(cls="Port", crate="pi-coding-agent", sha256="151a2c2a2724e4b09858218a0cb6c9c076fd987080c934597699ab3956a27cf6", rust_module="crates/pi-coding-agent/src/utils/tool_result_images.rs", adaptations=[], reason="Normalizes images in tool results (`_afterToolCall`)"),
    C + "utils/image-resize.ts": dict(cls="Adapt", crate="pi-coding-agent", sha256="d93a007eb45a02b73b1a4777d193614dae5fbcadd9139c8b755ea35c1d649757", rust_module="crates/pi-coding-agent/src/utils/image_resize.rs", adaptations=[], reason="`resizeImage` and dimension notes; the worker-thread path becomes `spawn_blocking`",
                                      cut=["ResizeImageWorkerResponse", "toTransferableBytes", "isResizeImageWorkerResponse", "createResizeWorker", "resizeImageInWorker"]),
    C + "utils/image-resize-core.ts": dict(cls="Adapt", crate="pi-coding-agent", sha256="b3523329397d47473b76c40e8802283a79d3a3e3f317f4da0124ccba5152edd8", rust_module="crates/pi-coding-agent/src/utils/image_resize_core.rs", adaptations=[], reason="Resize/encode candidate search; Photon calls become the `image` crate"),
    C + "utils/exif-orientation.ts": dict(cls="Adapt", crate="pi-coding-agent", sha256="fbca93e04682d00139c319a0721417d47b505e0c6e5787f4d9d9dba164194ad0", rust_module="crates/pi-coding-agent/src/utils/exif_orientation.rs", adaptations=[], reason="EXIF parsing ported as is; Photon rotation becomes the `image` crate"),
    C + "utils/mime.ts": dict(cls="Port", crate="pi-coding-agent", sha256="561d5511a976cdf4fc2d1b2ac773b21820bbad62e954e39c473f77c46a77f0af", rust_module="crates/pi-coding-agent/src/utils/mime.rs", adaptations=[], reason="Image type sniffing"),
    C + "utils/image-convert.ts": dict(cls="Adapt", crate="pi-coding-agent", sha256="5c61e36a267b9bbd5beeb2bb3f2a0938ed7a05f7333d4a17355ea807fc7bcd3b", rust_module="crates/pi-coding-agent/src/utils/image_convert.rs", adaptations=[], reason="`convertImageBytesToPng`; the pi-tui terminal transcoder registration goes",
                                       cut=["loadPngTranscoder", "pngTranscoderLoad", "pngTranscoderRegistered", "ensurePngTranscoder"], ranges=["1-1"]),
    # ---------------- pi-mcp ----------------
    "packages/mcp/src/protocol/content.ts": dict(cls="Adapt", crate="pi-mcp", sha256="a7c5d6e79fd3ce841a36fcfff7b5ab281305dac5466929a28a963a7b7709f63d", rust_module="crates/pi-mcp/src/protocol/content.rs", adaptations=[], reason="Hand port of `toLlmContent`/`blockToLlmContent` (lines 72-116), which the MCP tool adapter calls; rmcp supplies the protocol types",
                                                 keep=["72-116"]),
}

API_NAMES = {
    "anthropic-messages": "Anthropic Messages protocol",
    "azure-openai-config": "Azure OpenAI configuration",
    "azure-openai-responses": "Azure OpenAI Responses protocol",
    "bedrock-converse-stream": "AWS Bedrock Converse protocol",
    "cloudflare-ai-binding": "Cloudflare Workers AI binding transport",
    "cloudflare-workers-ai-system-one": "Cloudflare System One classifier",
    "cloudflare": "Cloudflare gateway helpers",
    "github-copilot-headers": "GitHub Copilot request headers (only for the Copilot provider; goes with `createClient`)",
    "google-generative-ai": "Google Gemini protocol",
    "google-shared": "Google shared conversion",
    "google-vertex": "Google Vertex protocol",
    "lazy": "Lazy API loaders for the provider registry",
    "llama-cpp-classify": "llama.cpp classifier",
    "mistral-conversations": "Mistral protocol",
    "openai-codex-responses": "OpenAI Codex (ChatGPT) Responses protocol",
    "openai-responses-shared": "OpenAI Responses conversion and stream parser",
    "openai-responses": "OpenAI Responses protocol",
    "openrouter-images": "OpenRouter image generation",
    "pi-messages": "Radius `pi-messages` protocol",
    "system-one-shared": "System One classifier helpers",
    "typesafe-system-one": "Typesafe System One classifier",
}

EXCLUDE_RULES = [
    # pi-agent-core
    (r"^packages/agent/src/index\.ts$", "Re-export barrel; the crate root re-exports the selected items"),
    (r"^packages/agent/src/proxy\.ts$", "`streamProxy` through an auth-holding server; nothing calls it; Maple's encrypted transport replaces it"),
    # pi-ai
    (r"^packages/ai/src/api/openai-completions\.lazy\.ts$", "Lazy loader for the global API registry (`compat.ts`), which is excluded"),
    (r"^packages/ai/src/api/.*\.lazy\.ts$", "Lazy loader for an excluded API"),
    (r"^packages/ai/src/api/", "API:"),
    (r"^packages/ai/src/auth/oauth/", "OAuth login for another provider; Maple authenticates with its OpenSecret session"),
    (r"^packages/ai/src/auth/", "Credential resolution/store for provider API keys; Maple's transport authenticates"),
    (r"^packages/ai/src/compat/", "OAuth types for extension custom providers (excluded)"),
    (r"^packages/ai/src/compat\.ts$", "Global API-provider registry and legacy `stream`/`complete`; registers every built-in API and imports generated data"),
    (r"^packages/ai/src/models\.generated\.ts$", "Generated model catalog; Maple supplies models (generated)"),
    (r"^packages/ai/src/providers/.*\.models\.ts$", "Generated per-provider catalog (generated)"),
    (r"^packages/ai/src/providers/all\.ts$", "Built-in provider registry; imports gitignored generated data"),
    (r"^packages/ai/src/providers/data-json\.d\.ts$", "Typing for gitignored generated catalog JSON"),
    (r"^packages/ai/src/providers/images/", "Image-generation provider registration"),
    (r"^packages/ai/src/providers/", "Provider definition for another vendor; inference goes only to Maple's backend"),
    (r"^packages/ai/src/index\.ts$", "Re-export barrel"),
    (r"^packages/ai/src/(bedrock-provider|bun-oauth|oauth)\.ts$", "Entry point for an excluded provider or OAuth"),
    (r"^packages/ai/src/cli\.ts$", "pi-ai command-line login helper"),
    (r"^packages/ai/src/env-api-keys\.ts$", "Provider API keys from environment variables"),
    (r"^packages/ai/src/(image-models|images|images-api-registry)\.ts$", "Image generation"),
    (r"^packages/ai/src/legacy-api-aliases\.ts$", "Legacy API name aliases"),
    (r"^packages/ai/src/(model-catalog|models-store)\.ts$", "Catalog refresh and model store; Maple's catalog replaces them"),
    (r"^packages/ai/src/utils/abort-signals\.ts$", "Abort helper used only by the Codex Responses protocol"),
    (r"^packages/ai/src/utils/abort\.ts$", "Abort helpers for the excluded `Models` registry and credential store"),
    (r"^packages/ai/src/utils/assistant-message-frame\.ts$", "Replayable message frames; no selected module uses them"),
    (r"^packages/ai/src/utils/error-body\.ts$", "SDK error-body normalization; Maple's adapter maps transport errors (error mapping stays in Maple)"),
    (r"^packages/ai/src/utils/models-error\.ts$", "`ModelsError` for the excluded registry and auth resolution"),
    (r"^packages/ai/src/utils/node-http-proxy\.ts$", "Node HTTP proxy agent for Bedrock/Codex"),
    (r"^packages/ai/src/utils/oauth-page\.ts$", "OAuth callback page"),
    (r"^packages/ai/src/utils/pi-user-agent\.ts$", "`User-Agent` header set in `createClient`; Maple's transport sets headers"),
    (r"^packages/ai/src/utils/provider-retry\.ts$", "HTTP-level retry; identity unless `maxRetries` is set (`provider-retry.ts:109`); retry stays in Maple's adapter"),
    (r"^packages/ai/src/utils/sleep\.ts$", "Sleep used only by OAuth device-code flows"),
    (r"^packages/ai/src/utils/typebox-helpers\.ts$", "TypeBox `StringEnum` helper; Rust schemas are JSON values"),
    # pi-coding-agent
    (r"^packages/coding-agent/src/modes/interactive/", "Terminal app (terminal UI is excluded)"),
    (r"^packages/coding-agent/src/modes/rpc/", "JSONL RPC mode; Maple's ACP server replaces it"),
    (r"^packages/coding-agent/src/modes/(print-mode|json-event)\.ts$", "Headless print/JSON modes (not in the first version)"),
    (r"^packages/coding-agent/src/modes/index\.ts$", "Re-export barrel for modes"),
    (r"^packages/coding-agent/src/(experimental|cli/experimental)/", "Unshipped experimental durable/remote code (out of scope)"),
    (r"^packages/coding-agent/src/client/", "Re-export of the experimental client"),
    (r"^packages/coding-agent/src/core/experimental\.ts$", "Experimental feature switch"),
    (r"^packages/coding-agent/src/cli/file-processor\.ts$", "`@file` attachments; Maple's attachments replace them"),
    (r"^packages/coding-agent/src/cli/", "CLI front end"),
    (r"^packages/coding-agent/src/(cli|main|migrations|package-manager-cli|rpc-entry)\.ts$", "CLI entry point, data migrations or `pi install` front end"),
    (r"^packages/coding-agent/src/bun/", "Bun binary support"),
    (r"^packages/coding-agent/src/index\.ts$", "Re-export barrel"),
    (r"^packages/coding-agent/src/core/index\.ts$", "Re-export barrel"),
    (r"^packages/coding-agent/src/core/extensions/index\.ts$", "Re-export barrel"),
    (r"^packages/coding-agent/src/core/compaction/index\.ts$", "Re-export barrel"),
    (r"^packages/coding-agent/src/core/extensions/(jiti-loader|jiti-static-loader|virtual-modules)\.ts$", "TypeScript extension loading via jiti"),
    (r"^packages/coding-agent/src/core/export-html/", "HTML session viewer"),
    (r"^packages/coding-agent/src/utils/html\.ts$", "HTML escaping for syntax highlighting / HTML export"),
    (r"^packages/coding-agent/src/core/tools/renderers/", "Terminal tool renderers"),
    (r"^packages/coding-agent/src/core/tools/render-utils\.ts$", "Terminal rendering helpers"),
    (r"^packages/coding-agent/src/core/tools/", "Pi built-in tool; Maple supplies its own tools"),
    (r"^packages/coding-agent/src/extensions/mcp/", "MCP extension module; Maple's rmcp layer replaces it"),
    (r"^packages/coding-agent/src/extensions/codemode/", "Codemode (deferred)"),
    (r"^packages/coding-agent/src/extensions/tool-search/", "`tool_search` for deferred MCP exposure (deferred with codemode)"),
    (r"^packages/coding-agent/src/extensions/llama/", "llama.cpp local models (not Maple inference)"),
    (r"^packages/coding-agent/src/extensions/index\.ts$", "CLI list of built-in extension factories"),
    (r"^packages/coding-agent/src/core/(model-runtime|model-config|model-resolver|models-store)\.ts$", "Model runtime, `models.json`, model patterns and catalog cache; Maple implements the `ModelRuntime` seam"),
    (r"^packages/coding-agent/src/core/auth-storage\.ts$", "`auth.json` credential store; Maple's OpenSecret auth replaces it"),
    (r"^packages/coding-agent/src/core/(runtime-credentials|resolve-config-value)\.ts$", "API keys and `$NAME`/`!command` config values; no API keys on Maple's path"),
    (r"^packages/coding-agent/src/core/auth-guidance\.ts$", "`/login` and Pi docs hints; call sites take host-supplied messages"),
    (r"^packages/coding-agent/src/core/(provider-composer|remote-catalog-provider|provider-attribution|radius|http-dispatcher)\.ts$", "Custom providers, pi.dev catalog refresh, attribution headers, Radius gateway or HTTP timeouts/proxy"),
    (r"^packages/coding-agent/src/utils/management-http\.ts$", "HTTP helper for pi.dev management calls"),
    (r"^packages/coding-agent/src/core/(cache-warmer|cache-stats)\.ts$", "Prompt-cache warming and cache-miss notices (deferred: backend cache lifetimes unknown)"),
    (r"^packages/coding-agent/src/core/nested-tool-calls\.ts$", "`ctx.executeTool()` nested calls"),
    (r"^packages/coding-agent/src/core/bash-executor\.ts$", "User `!`/`!!` shell commands"),
    (r"^packages/coding-agent/src/core/(bug-report|bug-report-upload|crash-log)\.ts$", "Bug reports and crash logs (vendor uploads)"),
    (r"^packages/coding-agent/src/core/(pi-manifest)\.ts$", "`pi` key in package manifests (installer)"),
    (r"^packages/coding-agent/src/core/(output-guard)\.ts$", "Stdout takeover for print/JSON modes"),
    (r"^packages/coding-agent/src/core/(keybindings|footer-data-provider)\.ts$", "Terminal keybindings / footer data"),
    (r"^packages/coding-agent/src/core/(telemetry|timings)\.ts$", "Install telemetry switch / startup timing (`time()` calls become no-ops, as with `PI_TIMING` unset)"),
    (r"^packages/coding-agent/src/core/(virtual-models)\.ts$", "Virtual models"),
    (r"^packages/coding-agent/src/utils/(child-process|shell)\.ts$", "Process spawning and shell lookup for built-in tools; Rust uses `tokio::process`"),
    (r"^packages/coding-agent/src/utils/tools-manager\.ts$", "Downloads `fd`/`rg`"),
    (r"^packages/coding-agent/src/utils/(image-resize-worker|photon)\.ts$", "Node worker entry / Photon wasm loader; `spawn_blocking` and the `image` crate replace them"),
    (r"^packages/coding-agent/src/utils/(clipboard|clipboard-command|clipboard-image|wsl)\.ts$", "Terminal clipboard support"),
    (r"^packages/coding-agent/src/utils/(syntax-highlight|highlight-js\.d|ansi|changelog|version-check|windows-self-update|zip|deprecation|json|open-browser|git|fs-watch|abort|pi-user-agent)\.ts$", "UTILS"),
]

UTIL_REASONS = {
    "syntax-highlight": "Terminal syntax highlighting",
    "highlight-js.d": "Type declarations for terminal syntax highlighting",
    "ansi": "ANSI stripping for user shell output and terminal renderers",
    "changelog": "Changelog display",
    "version-check": "pi.dev version check; Maple's release check replaces it",
    "windows-self-update": "Windows self-update",
    "zip": "Zip writer for bug reports",
    "deprecation": "Deprecation warnings (no importers)",
    "json": "JSON helper for `models.json`",
    "open-browser": "Opens the browser for MCP OAuth",
    "git": "Git source parsing for the installer",
    "fs-watch": "File watching for the footer and themes",
    "abort": "Abort helpers for the model runtime and auth storage",
    "pi-user-agent": "User-Agent for pi.dev calls",
}

EXCLUDE_OVERRIDES = {
    I + "auth/context.ts": "Default auth context for the `Models` registry",
    I + "auth/credential-store.ts": "Credential-store contract and in-memory store",
    I + "auth/helpers.ts": "`envApiKeyAuth` and similar provider auth builders",
    I + "auth/resolve.ts": "Provider auth resolution and OAuth refresh",
    I + "providers/opencode-headers.ts": "OpenCode session header helper for that provider",
    I + "providers/cloudflare-auth.ts": "Cloudflare provider auth",
    I + "providers/cloudflare-stream.ts": "Cloudflare provider stream wrapper",
    I + "providers/radius-config.ts": "Radius gateway provider configuration",
    C + "core/provider-composer.ts": "Composes providers from `models.json` and extensions (custom providers excluded)",
    C + "core/remote-catalog-provider.ts": "pi.dev model-catalog refresh every 4 hours",
    C + "core/provider-attribution.ts": "Attribution headers merged in `sdk.ts` `transformHeaders`; cut there",
    C + "core/radius.ts": "Radius gateway constants",
    C + "core/http-dispatcher.ts": "undici HTTP timeouts and proxy; Maple's transport owns network settings",
    C + "core/model-config.ts": "`models.json` custom endpoints and overrides",
    C + "core/model-resolver.ts": "Model patterns, scoped models and `findInitialModel`; Maple passes the model",
    C + "core/model-runtime.ts": "Provider/auth/catalog runtime; replaced by a `ModelRuntime` trait Maple implements",
    C + "core/models-store.ts": "File-backed model catalog cache",
    C + "core/runtime-credentials.ts": "Runtime API keys",
    C + "core/resolve-config-value.ts": "`$NAME` and `!command` configuration values",
    C + "core/telemetry.ts": "Install-telemetry switch (Maple has no telemetry)",
    C + "core/timings.ts": "Startup timing; `time()`/`resetTimings()` call sites become no-ops, as when `PI_TIMING` is unset (`timings.ts:6`)",
    C + "core/keybindings.ts": "Terminal keybindings",
    C + "core/bug-report.ts": "`/bug` report builder (vendor upload)",
    C + "core/bug-report-upload.ts": "Uploads bug reports to `radius.pi.dev`",
    C + "core/crash-log.ts": "Crash records for bug reports",
    C + "core/cache-warmer.ts": "Prompt-cache warming (deferred: backend cache lifetimes unknown)",
    C + "core/cache-stats.ts": "Cache-miss notices (deferred with cache warming)",
    C + "core/session-export.ts": "",
    C + "cli/file-processor.ts": "`@file` attachments; Maple's attachments replace them",
    C + "modes/print-mode.ts": "Print mode (headless; not in the first version)",
    C + "modes/json-event.ts": "JSONL event stream mode (headless; not in the first version)",
    I + "bedrock-provider.ts": "Bedrock provider entry point",
    I + "bun-oauth.ts": "Bun OAuth entry point",
    I + "oauth.ts": "OAuth entry point",
}
